### ISSUE TITLE
Does not build on latest stable Rust (1.55)

### ISSUE THREAD

**Issue by maackle** [ptal/gcollections#3]
`bit-set 0.2.x` does not compile with the latest stable Rust (1.55). It looks like this crate needs to update its `bit-set` dependency in order to maintain compatibility with stable Rust.

Is this crate still maintained? We are using it in https://github.com/holochain/holochain, and we will need to create a fork soon if this isn't fixed upstream.

**Comment by ptal** [comment]
Sure, if this crate is used by someone, I can maintain it ;-) If it's easy, you can also submit a pull request.
I'll look into that under a few days.
